services:
  - type: web
    name: setgame-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: setgame-python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
